{{ if and .Values.operator .Values.controlPlane.enabled .Values.memberRoll.enabled -}}
---
apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: {{ .Values.memberRoll.name }}
  namespace: {{ .Values.controlPlane.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  members:
    {{- range .Values.memberRoll.members }}
    - {{ . }}
    {{- end }}
{{- end }}
