{{ if and .Values.operator .Values.knativeServing.enabled -}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.knativeServing.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: {{ .Values.knativeServing.name }}
  namespace: {{ .Values.knativeServing.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec: {}
{{- end }}
