---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  slack-bot-token: {{ .Values.slackBotToken }}
  slack-team-id: {{ .Values.slackTeamId }}
  granite-token: {{ .Values.graniteToken }}
  llama-token: {{ .Values.llamaToken }}
