---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.slack_mcp_server_secrets.name }}
  namespace: {{ .Values.slack_mcp_server_secrets.namespace }}
type: Opaque
stringData:
  slack_bot_token: {{ .Values.slack_mcp_server_secrets.slack_bot_token }}
  slack_team_id: {{ .Values.slack_mcp_server_secrets.slack_team_id }}
